# Generated by Django 4.0.1 on 2022-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_text', models.TextField()),
                ('creator', models.EmailField(max_length=254)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id_string', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
