# Generated by Django 4.0.1 on 2022-01-31 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markdown_text', models.TextField()),
                ('creator', models.EmailField(max_length=254)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
