# Generated by Django 4.0.1 on 2022-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(max_length=16)),
                ('markdown_text', models.TextField()),
                ('creator', models.EmailField(max_length=254)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
