# Generated by Django 4.0.1 on 2022-01-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id_string',
            new_name='identifier',
        ),
    ]
