# Generated by Django 4.0.1 on 2022-01-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0002_rename_id_string_document_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='identifier',
            new_name='key',
        ),
    ]
