# Generated by Django 4.0.1 on 2022-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0003_rename_identifier_document_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='key',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
