# Generated by Django 4.0.1 on 2022-01-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0004_alter_document_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='key',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
